
spring:
  application:
      name: profile-services
  datasource.url: "jdbc:mysql://localhost:3306/realestate?autoreconnect=true"
  datasource.username: root
  datasource.password: ""
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: concreate.realtor@gmail.com
    password: Kalpana304#
    properties:
      mail:
        debug: true
        transport.protocol: smtp
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls.enable: true

server:
  port: 8085

eureka.client.service-url.defaultZone: http://localhost:8761/eureka/

db-queries:
  findAllProfile: "select * from profile"
  findProfile: "select * from profile where emailid=?"
  insertProfile: "Insert INTO profile (firstname,lastname,contact,emailid,password,address,city,roleid,status) VALUES (?,?,?,?,?,?,?,?,?)"
  updateProfile:  "update profile set firstname=?,lastname=?, contact=?, emailid=?,password=?,address=?,city=?,roleid=?,status=? where id=?"
  updateDefaultPassword: "update profile set password=? where emailid=?"