server:
  port:8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/realestate?serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: project-service


