spring:
  application.name: "auth-services"

  datasource.url: "jdbc:mysql://localhost:3306/realestate?autoreconnect=true"
  datasource.username: root
  datasource.password: ""
  datasource:
    driver-class-name: com.mysql.jdbc.Driver

db-queries :
  findProfileByUserName: "select * from profile where emailid=?"

server:
  port: 8082

eureka.client.service-url.defaultZone: http://localhost:8761/eureka/